version: '3.8'

services:
  app:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: hr_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=hrdb;Username=postgres;Password=postgres

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: